import type { ModelOption } from "./models.js";

export const EXTERNAL_MODELS: ModelOption[] = [
  {
    id: "openai/gpt-4.1-mini",
    provider: "OpenAI",
    description: "Fast, low-cost GPT-4.1 variant with a 1M-token context window and image input.",
    contextWindow: 1047576,
    pricePerMInput: 0.4,
    pricePerMOutput: 1.6,
    reasoning: false,
    functionCalling: true,
    vision: true,
  },
  {
    id: "openai/gpt-5-mini",
    provider: "OpenAI",
    description: "Smaller GPT-5 reasoning model; thinks before answering, so first tokens arrive later.",
    contextWindow: 400000,
    pricePerMInput: 0.25,
    pricePerMOutput: 2,
    reasoning: true,
    functionCalling: true,
    vision: true,
  },
  {
    id: "anthropic/claude-haiku-4-5",
    provider: "Anthropic",
    description: "Anthropic's fastest model, near-frontier coding quality at low cost.",
    contextWindow: 200000,
    pricePerMInput: 1,
    pricePerMOutput: 5,
    reasoning: false,
    functionCalling: true,
    vision: true,
  },
  {
    id: "anthropic/claude-sonnet-4-6",
    provider: "Anthropic",
    description: "Anthropic's balanced model for complex reasoning, writing and coding.",
    contextWindow: 200000,
    pricePerMInput: 3,
    pricePerMOutput: 15,
    reasoning: true,
    functionCalling: true,
    vision: true,
  },
  {
    id: "google-ai-studio/gemini-2.5-flash",
    provider: "Google",
    description: "Google's price-performance Gemini model with a 1M-token context window.",
    contextWindow: 1000000,
    pricePerMInput: 0.3,
    pricePerMOutput: 2.5,
    reasoning: true,
    functionCalling: true,
    vision: true,
  },
  {
    id: "google-ai-studio/gemini-2.5-pro",
    provider: "Google",
    description: "Google's most capable Gemini 2.5 model for deep reasoning over long inputs.",
    contextWindow: 1000000,
    pricePerMInput: 1.25,
    pricePerMOutput: 10,
    reasoning: true,
    functionCalling: true,
    vision: true,
  },
];
