// GENERATED by scripts/sync-models.mjs -- do not hand-edit.
// Regenerate with: pnpm run models:sync
//
// Source of truth is Cloudflare's actual Workers AI catalog (via
// `wrangler ai models list/schema`), not hand-picked ids from docs pages.
// Filtered to models whose schema accepts the chat `messages` format;
// excludes non-conversational models mistagged under the same task (see
// EXCLUDED_NAME_PATTERNS in the sync script).
export interface ModelOption {
  id: string;
  provider: string;
  description: string;
  contextWindow: number | null;
  pricePerMInput: number | null;
  pricePerMOutput: number | null;
  reasoning: boolean;
  functionCalling: boolean;
  vision: boolean;
}

export const DEFAULT_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast";

export const MODELS: ModelOption[] = [
  {
    "id": "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
    "provider": "aisingapore",
    "description": "SEA-LION stands for Southeast Asian Languages In One Network, which is a collection of Large Language Models (LLMs) which have been pretrained and instruct-tuned for the Southeast Asia (SEA) region.",
    "contextWindow": 128000,
    "pricePerMInput": 0.351,
    "pricePerMOutput": 0.555,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    "provider": "deepseek-ai",
    "description": "DeepSeek-R1-Distill-Qwen-32B is a model distilled from DeepSeek-R1 based on Qwen2.5. It outperforms OpenAI-o1-mini across various benchmarks, achieving new state-of-the-art results for dense models.",
    "contextWindow": 80000,
    "pricePerMInput": 0.497,
    "pricePerMOutput": 4.881,
    "reasoning": true,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/deepseek-ai/deepseek-v4-flash-0731",
    "provider": "deepseek-ai",
    "description": "DeepSeek-V4-Flash-0731 is the official release of DeepSeek-V4-Flash, superseding the preview version, with substantially enhanced agentic capabilities. ",
    "contextWindow": 1310720,
    "pricePerMInput": 0.44,
    "pricePerMOutput": 1.32,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/deepseek-ai/deepseek-v4-pro-0813",
    "provider": "deepseek-ai",
    "description": "DeepSeek V4 Pro is a high-capability reasoning model from DeepSeek with a one million token context window, built for long-horizon agentic workflows and complex, multi-step problem-solving",
    "contextWindow": 1048576,
    "pricePerMInput": 1.32,
    "pricePerMOutput": 3.96,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/google/gemma-2b-it-lora",
    "provider": "google",
    "description": "This is a Gemma-2B base model that Cloudflare dedicates for inference with LoRA adapters. Gemma is a family of lightweight, state-of-the-art open models from Google, built from the same research and technology used to create the Gemini models.",
    "contextWindow": 8192,
    "pricePerMInput": null,
    "pricePerMOutput": null,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/google/gemma-4-26b-a4b-it",
    "provider": "google",
    "description": "Gemma 4 is Google's most intelligent family of open models, built from Gemini 3 research to maximize intelligence-per-parameter.",
    "contextWindow": 256000,
    "pricePerMInput": 0.1,
    "pricePerMOutput": 0.3,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/google/gemma-7b-it-lora",
    "provider": "google",
    "description": "  This is a Gemma-7B base model that Cloudflare dedicates for inference with LoRA adapters. Gemma is a family of lightweight, state-of-the-art open models from Google, built from the same research and technology used to create the Gemini models.",
    "contextWindow": 3500,
    "pricePerMInput": null,
    "pricePerMOutput": null,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/ibm-granite/granite-4.0-h-micro",
    "provider": "ibm-granite",
    "description": "Granite 4.0 instruct models deliver strong performance across benchmarks, achieving industry-leading results in key agentic tasks like instruction following and function calling. These efficiencies make the models well-suited for a wide range of use cases like retrieval-augmented generation (RAG), multi-agent workflows, and edge deployments.",
    "contextWindow": 131000,
    "pricePerMInput": 0.017,
    "pricePerMOutput": 0.112,
    "reasoning": false,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/meta/llama-3.1-8b-instruct-fp8",
    "provider": "meta",
    "description": "Llama 3.1 8B quantized to FP8 precision",
    "contextWindow": 32000,
    "pricePerMInput": 0.152,
    "pricePerMOutput": 0.287,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/meta/llama-3.2-11b-vision-instruct",
    "provider": "meta",
    "description": " The Llama 3.2-Vision instruction-tuned models are optimized for visual recognition, image reasoning, captioning, and answering general questions about an image.",
    "contextWindow": 128000,
    "pricePerMInput": 0.0485,
    "pricePerMOutput": 0.676,
    "reasoning": false,
    "functionCalling": false,
    "vision": true
  },
  {
    "id": "@cf/meta/llama-3.2-1b-instruct",
    "provider": "meta",
    "description": "The Llama 3.2 instruction-tuned text only models are optimized for multilingual dialogue use cases, including agentic retrieval and summarization tasks.",
    "contextWindow": 60000,
    "pricePerMInput": 0.027,
    "pricePerMOutput": 0.201,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/meta/llama-3.2-3b-instruct",
    "provider": "meta",
    "description": "The Llama 3.2 instruction-tuned text only models are optimized for multilingual dialogue use cases, including agentic retrieval and summarization tasks.",
    "contextWindow": 80000,
    "pricePerMInput": 0.0509,
    "pricePerMOutput": 0.335,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    "provider": "meta",
    "description": "Llama 3.3 70B quantized to fp8 precision, optimized to be faster.",
    "contextWindow": 24000,
    "pricePerMInput": 0.293,
    "pricePerMOutput": 2.253,
    "reasoning": false,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/meta/llama-4-scout-17b-16e-instruct",
    "provider": "meta",
    "description": "Meta's Llama 4 Scout is a 17 billion parameter model with 16 experts that is natively multimodal. These models leverage a mixture-of-experts architecture to offer industry-leading performance in text and image understanding.",
    "contextWindow": 131000,
    "pricePerMInput": 0.27,
    "pricePerMOutput": 0.85,
    "reasoning": false,
    "functionCalling": true,
    "vision": true
  },
  {
    "id": "@cf/meta-llama/llama-2-7b-chat-hf-lora",
    "provider": "meta-llama",
    "description": "This is a Llama2 base model that Cloudflare dedicated for inference with LoRA adapters. Llama 2 is a collection of pretrained and fine-tuned generative text models ranging in scale from 7 billion to 70 billion parameters. This is the repository for the 7B fine-tuned model, optimized for dialogue use cases and converted for the Hugging Face Transformers format. ",
    "contextWindow": 8192,
    "pricePerMInput": null,
    "pricePerMOutput": null,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/mistral/mistral-7b-instruct-v0.2-lora",
    "provider": "mistral",
    "description": "The Mistral-7B-Instruct-v0.2 Large Language Model (LLM) is an instruct fine-tuned version of the Mistral-7B-v0.2.",
    "contextWindow": 15000,
    "pricePerMInput": null,
    "pricePerMOutput": null,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/mistralai/mistral-small-3.1-24b-instruct",
    "provider": "mistralai",
    "description": "Building upon Mistral Small 3 (2501), Mistral Small 3.1 (2503) adds state-of-the-art vision understanding and enhances long context capabilities up to 128k tokens without compromising text performance. With 24 billion parameters, this model achieves top-tier capabilities in both text and vision tasks.",
    "contextWindow": 128000,
    "pricePerMInput": 0.351,
    "pricePerMOutput": 0.555,
    "reasoning": false,
    "functionCalling": true,
    "vision": true
  },
  {
    "id": "@cf/moonshotai/kimi-k2.6",
    "provider": "moonshotai",
    "description": "Kimi K2.6 is a frontier-scale open-source 1T parameter model with a 262.1k context window, multi-turn tool calling, vision inputs, and structured outputs for agentic workloads.",
    "contextWindow": 262144,
    "pricePerMInput": 0.95,
    "pricePerMOutput": 4,
    "reasoning": true,
    "functionCalling": true,
    "vision": true
  },
  {
    "id": "@cf/moonshotai/kimi-k2.7-code",
    "provider": "moonshotai",
    "description": "Kimi K2.7 is a frontier-scale open-source 1T parameter model with a 262.1k context window, multi-turn tool calling, vision inputs, and structured outputs for agentic workloads.",
    "contextWindow": 262144,
    "pricePerMInput": 0.95,
    "pricePerMOutput": 4,
    "reasoning": true,
    "functionCalling": true,
    "vision": true
  },
  {
    "id": "@cf/nvidia/nemotron-3-120b-a12b",
    "provider": "nvidia",
    "description": "NVIDIA Nemotron 3 Super is a hybrid MoE model with leading accuracy for multi-agent applications and specialized agentic AI systems.",
    "contextWindow": 256000,
    "pricePerMInput": 0.5,
    "pricePerMOutput": 1.5,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/openai/gpt-oss-120b",
    "provider": "openai",
    "description": "OpenAI’s open-weight models designed for powerful reasoning, agentic tasks, and versatile developer use cases – gpt-oss-120b is for production, general purpose, high reasoning use-cases.",
    "contextWindow": 128000,
    "pricePerMInput": 0.35,
    "pricePerMOutput": 0.75,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/openai/gpt-oss-20b",
    "provider": "openai",
    "description": "OpenAI’s open-weight models designed for powerful reasoning, agentic tasks, and versatile developer use cases – gpt-oss-20b is for lower latency, and local or specialized use-cases.",
    "contextWindow": 128000,
    "pricePerMInput": 0.2,
    "pricePerMOutput": 0.3,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/qwen/qwen2.5-coder-32b-instruct",
    "provider": "qwen",
    "description": "Qwen2.5-Coder is the latest series of Code-Specific Qwen large language models (formerly known as CodeQwen). As of now, Qwen2.5-Coder has covered six mainstream model sizes, 0.5, 1.5, 3, 7, 14, 32 billion parameters, to meet the needs of different developers. Qwen2.5-Coder brings the following improvements upon CodeQwen1.5:",
    "contextWindow": 32768,
    "pricePerMInput": 0.66,
    "pricePerMOutput": 1,
    "reasoning": false,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/qwen/qwen3-30b-a3b-fp8",
    "provider": "qwen",
    "description": "Qwen3 is the latest generation of large language models in Qwen series, offering a comprehensive suite of dense and mixture-of-experts (MoE) models. Built upon extensive training, Qwen3 delivers groundbreaking advancements in reasoning, instruction-following, agent capabilities, and multilingual support.",
    "contextWindow": 32768,
    "pricePerMInput": 0.0509,
    "pricePerMOutput": 0.335,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/qwen/qwen3.8-27b",
    "provider": "qwen",
    "description": "Qwen 3.8 27B is a 27-billion-parameter instruction-tuned language model from Alibaba's Qwen family, designed for vision, efficient general-purpose text generation and agentic workloads.",
    "contextWindow": 262144,
    "pricePerMInput": 0.45,
    "pricePerMOutput": 3.2,
    "reasoning": true,
    "functionCalling": true,
    "vision": true
  },
  {
    "id": "@cf/qwen/qwq-32b",
    "provider": "qwen",
    "description": "QwQ is the reasoning model of the Qwen series. Compared with conventional instruction-tuned models, QwQ, which is capable of thinking and reasoning, can achieve significantly enhanced performance in downstream tasks, especially hard problems. QwQ-32B is the medium-sized reasoning model, which is capable of achieving competitive performance against state-of-the-art reasoning models, e.g., DeepSeek-R1, o1-mini.",
    "contextWindow": 24000,
    "pricePerMInput": 0.66,
    "pricePerMOutput": 1,
    "reasoning": true,
    "functionCalling": false,
    "vision": false
  },
  {
    "id": "@cf/zai-org/glm-4.7-flash",
    "provider": "zai-org",
    "description": "GLM-4.7-Flash is a fast and efficient multilingual text generation model with a 131,072 token context window. Optimized for dialogue, instruction-following, and multi-turn tool calling across 100+ languages.",
    "contextWindow": 131072,
    "pricePerMInput": 0.0605,
    "pricePerMOutput": 0.4,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/zai-org/glm-5.2",
    "provider": "zai-org",
    "description": "Z.ai's flagship agentic coding model",
    "contextWindow": 262144,
    "pricePerMInput": 1.4,
    "pricePerMOutput": 4.4,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/zai-org/glm-5.3",
    "provider": "zai-org",
    "description": "GLM-5.3 is Z.ai's flagship agentic coding model, pairing a 1M-token context window with reasoning, function calling, and structured outputs to power multi-step, tool-driven development workflows.",
    "contextWindow": 1310720,
    "pricePerMInput": 1.4,
    "pricePerMOutput": 4.4,
    "reasoning": true,
    "functionCalling": true,
    "vision": false
  },
  {
    "id": "@cf/zai-org/glm-5.3-flash",
    "provider": "zai-org",
    "description": "The first natively multimodal model in the GLM-5 series. With 320B total parameters and just 18B active parameters, it outperforms GLM-5.2 across benchmarks and real-world workloads at one-tenth the price, while approaching Claude Opus 4.8 on coding and agentic benchmarks.",
    "contextWindow": 1310720,
    "pricePerMInput": 0.15,
    "pricePerMOutput": 0.5,
    "reasoning": true,
    "functionCalling": true,
    "vision": true
  }
];

export function isValidModel(id: string): boolean {
  return MODELS.some((m) => m.id === id);
}

export function findModel(id: string): ModelOption | undefined {
  return MODELS.find((m) => m.id === id);
}
