#!/usr/bin/env node
// Regenerates shared/models.ts from Cloudflare's real Workers AI catalog,
// instead of hand-picking model ids from documentation pages. Run:
//   pnpm run models:sync
//
// Filters the full "Text Generation" catalog down to models that actually
// support the chat `messages` format (some only accept a plain `prompt`
// string) and excludes non-conversational models that are mistagged under
// the same task (e.g. llama-guard-3-8b is a safety classifier, not a chat
// model). Detects vision/multimodal support by checking whether the
// model's `messages` schema accepts `image_url` content.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

// Known non-chat models mistagged under "Text Generation" in the catalog.
const EXCLUDED_NAME_PATTERNS = [/guard/i];

function wrangler(args) {
  return execFileSync("wrangler", args, {
    cwd: new URL("..", import.meta.url),
    stdio: ["ignore", "pipe", "pipe"],
    encoding: "utf-8",
    maxBuffer: 1024 * 1024 * 16,
  });
}

function findVariants(node, out = []) {
  if (Array.isArray(node)) {
    for (const item of node) findVariants(item, out);
  } else if (node && typeof node === "object") {
    if (Array.isArray(node.oneOf)) {
      for (const o of node.oneOf) {
        if (o && typeof o === "object" && "title" in o) out.push(o);
      }
    }
    for (const value of Object.values(node)) findVariants(value, out);
  }
  return out;
}

// Cloudflare's schema generator reuses one generic OpenAI-compatible message
// shape across most chat models, so `image_url` shows up in the schema even
// for text-only models (e.g. qwq-32b, a pure reasoning model) that were
// never trained on images and will error or ignore it. Schema support alone
// is a necessary but not sufficient signal -- require the catalog's own
// description to actually claim vision/multimodal capability too.
const VISION_DESCRIPTION_PATTERN = /vision|multimodal|visual recognition|image reasoning/i;

function inspectSchema(modelId) {
  const raw = wrangler(["ai", "models", "schema", modelId]);
  const schema = JSON.parse(raw);
  const variants = findVariants(schema.input ?? {});
  const messagesVariant = variants.find((v) => v.title === "Messages");
  if (!messagesVariant) return { supportsChat: false, acceptsImageUrl: false };

  const messagesSchema = JSON.stringify(messagesVariant.properties?.messages ?? {});
  return { supportsChat: true, acceptsImageUrl: messagesSchema.includes("image_url") };
}

function propValue(model, id) {
  return model.properties?.find((p) => p.property_id === id)?.value;
}

console.log("Fetching Text Generation catalog...");
const catalog = JSON.parse(
  wrangler(["ai", "models", "list", "--task", "Text Generation", "--hide-experimental", "--json"])
);

const models = [];
for (const model of catalog) {
  if (EXCLUDED_NAME_PATTERNS.some((re) => re.test(model.name))) {
    console.log(`skip (excluded pattern): ${model.name}`);
    continue;
  }

  process.stdout.write(`checking ${model.name}... `);
  let inspected;
  try {
    inspected = inspectSchema(model.name);
  } catch (err) {
    console.log(`schema fetch failed, skipping (${err.message})`);
    continue;
  }
  if (!inspected.supportsChat) {
    console.log("no Messages format, skipping");
    continue;
  }
  const vision = inspected.acceptsImageUrl && VISION_DESCRIPTION_PATTERN.test(model.description);
  console.log(vision ? "OK (vision)" : "OK");

  const price = propValue(model, "price") ?? [];
  const input = price.find((p) => p.unit.includes("input"))?.price ?? null;
  const output = price.find((p) => p.unit.includes("output"))?.price ?? null;

  models.push({
    id: model.name,
    provider: model.name.split("/")[1],
    description: model.description,
    contextWindow: Number(propValue(model, "context_window")) || null,
    pricePerMInput: input,
    pricePerMOutput: output,
    reasoning: propValue(model, "reasoning") === "true",
    functionCalling: propValue(model, "function_calling") === "true",
    vision,
  });
}

models.sort((a, b) => a.provider.localeCompare(b.provider) || a.id.localeCompare(b.id));

const output = `// GENERATED by scripts/sync-models.mjs -- do not hand-edit.
// Regenerate with: pnpm run models:sync
//
// Source of truth is Cloudflare's actual Workers AI catalog (via
// \`wrangler ai models list/schema\`), not hand-picked ids from docs pages.
// Filtered to models whose schema accepts the chat \`messages\` format;
// excludes non-conversational models mistagged under the same task (see
// EXCLUDED_NAME_PATTERNS in the sync script).
export interface ModelOption {
  id: string;
  provider: string;
  description: string;
  contextWindow: number | null;
  pricePerMInput: number | null;
  pricePerMOutput: number | null;
  reasoning: boolean;
  functionCalling: boolean;
  vision: boolean;
}

export const DEFAULT_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast";

export const MODELS: ModelOption[] = ${JSON.stringify(models, null, 2)};

export function isValidModel(id: string): boolean {
  return MODELS.some((m) => m.id === id);
}

export function findModel(id: string): ModelOption | undefined {
  return MODELS.find((m) => m.id === id);
}
`;

writeFileSync(new URL("../shared/models.ts", import.meta.url), output);
console.log(`\nWrote ${models.length} models to shared/models.ts`);
